### PR TITLE
Bumps dependencies

### PR DESCRIPTION
**Pull request by rentry**
This PR bumps dependencies. I had some issues getting the repo running locally on my new machine, requiring these updates.

We should make sure this branch clears on Netlify before merging.

### CODE REVIEW

**Comment by dpulitano** [comment]
Hey, for some reason it has been hanging for a few minutes when installing
dependencies when I'm testing building on Netlify. I can look into this
some... one theory is the version of Ruby or bundle running on Netlify
right now is incompatible and we have to make sure to pin the version. I'm
happy to look at this some this week.

Also, once we make sure that's working, I'm happy continuing on setting up
the Netlify <-> GitHub branch previews on PRs

Best

**Comment by dpulitano** [comment]
Actually, it ended up completing -- it just hung for 4 minutes which I didn't experience back in the Fall.

This is the deployed site: https://upbeat-wescoff-f0d870.netlify.app

And the deploy logs:
9:07:26 PM: Waiting for other deploys from your team to complete
9:07:37 PM: Build ready to start
9:07:41 PM: build-image version: 53b83b6bede2920f236b25b6f5a95334320dc849
9:07:41 PM: build-image tag: v3.6.0
9:07:41 PM: buildbot version: 7d7f8cd4cc19a5205bae0ea8df58feec103fed05
9:07:41 PM: Fetching cached dependencies
9:07:41 PM: Failed to fetch cache, continuing with build
9:07:41 PM: Starting to prepare the repo for build
9:07:41 PM: No cached dependencies found. Cloning fresh repo
9:07:41 PM: git clone https://github.com/dpulitano/maineballot
9:07:45 PM: Preparing Git Reference refs/heads/bump-dependencies
9:07:47 PM: Starting build script
9:07:47 PM: Installing dependencies
9:07:47 PM: Python version set to 2.7
9:07:48 PM: v12.18.0 is already installed.
9:07:49 PM: Now using node v12.18.0 (npm v6.14.4)
9:07:49 PM: Started restoring cached build plugins
9:07:49 PM: Finished restoring cached build plugins
9:07:49 PM: Attempting ruby version 2.7.1, read from environment
9:07:50 PM: Using ruby version 2.7.1
9:07:50 PM: Using bundler version 2.2.3 from Gemfile.lock
9:07:51 PM: Successfully installed bundler-2.2.3
9:07:51 PM: 1 gem installed
9:07:51 PM: Using PHP version 5.6
9:07:51 PM: Started restoring cached ruby gems
9:07:51 PM: Finished restoring cached ruby gems
9:07:51 PM: Installing gem bundle
9:07:52 PM: [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '/opt/build/cache/bundle'`, and stop using this flag
9:07:52 PM: [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
9:07:54 PM: Fetching gem metadata from https://rubygems.org/.........
9:07:54 PM: Using bundler 2.2.3
9:07:54 PM: Fetching zeitwerk 2.4.2
9:07:54 PM: Fetching public_suffix 4.0.6
9:07:54 PM: Fetching minitest 5.14.3
9:07:54 PM: Fetching eventmachine 1.2.7
9:07:54 PM: Fetching concurrent-ruby 1.1.7
9:07:54 PM: Fetching colorator 1.1.0
9:07:54 PM: Fetching http_parser.rb 0.6.0
9:07:54 PM: Fetching faraday-net_http 1.0.1
9:07:54 PM: Installing zeitwerk 2.4.2
9:07:54 PM: Installing colorator 1.1.0
9:07:54 PM: Installing faraday-net_http 1.0.1
9:07:54 PM: Fetching multipart-post 2.1.1
9:07:54 PM: Installing public_suffix 4.0.6
9:07:54 PM: Installing http_parser.rb 0.6.0 with native extensions
9:07:54 PM: Installing minitest 5.14.3
9:07:54 PM: Fetching ruby2_keywords 0.0.2
9:07:54 PM: Installing eventmachine 1.2.7 with native extensions
9:07:54 PM: Installing concurrent-ruby 1.1.7
9:07:54 PM: Fetching ffi 1.14.2
9:07:54 PM: Installing multipart-post 2.1.1
9:07:54 PM: Installing ruby2_keywords 0.0.2
9:07:55 PM: Fetching forwardable-extended 2.6.0
9:07:55 PM: Fetching gemoji 3.0.1
9:07:55 PM: Fetching mini_portile2 2.5.0
9:07:55 PM: Fetching racc 1.5.2
9:07:55 PM: Installing forwardable-extended 2.6.0
9:07:55 PM: Installing gemoji 3.0.1
9:07:55 PM: Installing mini_portile2 2.5.0
9:07:55 PM: Installing ffi 1.14.2 with native extensions
9:07:55 PM: Fetching rb-fsevent 0.10.4
9:07:55 PM: Installing racc 1.5.2 with native extensions
9:07:55 PM: Installing rb-fsevent 0.10.4
9:08:18 PM: Fetching liquid 4.0.3
9:08:18 PM: Fetching rouge 3.26.0
9:08:18 PM: Fetching rexml 3.2.4
9:08:18 PM: Fetching mercenary 0.4.0
9:08:18 PM: Installing mercenary 0.4.0
9:08:18 PM: Installing rexml 3.2.4
9:08:18 PM: Installing liquid 4.0.3
9:08:19 PM: Installing rouge 3.26.0
9:08:19 PM: Fetching safe_yaml 1.0.5
9:08:19 PM: Fetching unicode-display_width 1.7.0
9:08:19 PM: Fetching jekyll-paginate 1.1.0
9:08:19 PM: Fetching faraday 1.3.0
9:08:19 PM: Fetching webrick 1.7.0
9:08:19 PM: Fetching addressable 2.7.0
9:08:19 PM: Fetching pathutil 0.16.2
9:08:19 PM: Fetching i18n 1.8.7
9:08:19 PM: Installing jekyll-paginate 1.1.0
9:08:19 PM: Installing safe_yaml 1.0.5
9:08:19 PM: Installing unicode-display_width 1.7.0
9:08:19 PM: Installing pathutil 0.16.2
9:08:20 PM: Installing i18n 1.8.7
9:08:20 PM: Installing faraday 1.3.0
9:08:20 PM: Installing addressable 2.7.0
9:08:20 PM: Installing webrick 1.7.0
9:08:20 PM: Fetching tzinfo 2.0.4
9:08:20 PM: Fetching sassc 2.4.0
9:08:20 PM: Installing tzinfo 2.0.4
9:08:20 PM: Fetching rb-inotify 0.10.1
9:08:20 PM: Fetching kramdown 2.3.0
9:08:20 PM: Fetching nokogiri 1.11.1
9:08:20 PM: Fetching em-websocket 0.5.2
9:08:20 PM: Installing sassc 2.4.0 with native extensions
9:08:20 PM: Installing rb-inotify 0.10.1
9:08:20 PM: Installing em-websocket 0.5.2
9:08:20 PM: Fetching terminal-table 2.0.0
9:08:20 PM: Fetching activesupport 6.1.1
9:08:20 PM: Fetching listen 3.4.1
9:08:20 PM: Installing kramdown 2.3.0
9:08:20 PM: Installing terminal-table 2.0.0
9:08:20 PM: Fetching sawyer 0.8.2
9:08:20 PM: Installing listen 3.4.1
9:08:20 PM: Installing sawyer 0.8.2
9:08:20 PM: Installing activesupport 6.1.1
9:08:21 PM: Fetching octokit 4.20.0
9:08:21 PM: Fetching jekyll-watch 2.2.1
9:08:21 PM: Installing octokit 4.20.0
9:08:21 PM: Installing jekyll-watch 2.2.1
9:08:22 PM: Installing nokogiri 1.11.1 with native extensions
9:12:42 PM: Fetching jekyll-gist 1.5.0
9:12:42 PM: Fetching kramdown-parser-gfm 1.1.0
9:12:42 PM: Fetching jekyll-sass-converter 2.1.0
9:12:42 PM: Fetching html-pipeline 2.14.0
9:12:42 PM: Installing kramdown-parser-gfm 1.1.0
9:12:42 PM: Installing jekyll-gist 1.5.0
9:12:42 PM: Installing jekyll-sass-converter 2.1.0
9:12:42 PM: Installing html-pipeline 2.14.0
9:12:42 PM: Fetching jekyll 4.2.0
9:12:42 PM: Installing jekyll 4.2.0
9:12:42 PM: Fetching jekyll-feed 0.15.1
9:12:42 PM: Fetching jekyll-sitemap 1.4.0
9:12:42 PM: Fetching jemoji 0.12.0
9:12:42 PM: Fetching jekyll-include-cache 0.2.1
9:12:42 PM: Installing jemoji 0.12.0
9:12:42 PM: Installing jekyll-include-cache 0.2.1
9:12:42 PM: Installing jekyll-sitemap 1.4.0
9:12:42 PM: Installing jekyll-feed 0.15.1
9:12:43 PM: Bundle complete! 8 Gemfile dependencies, 50 gems now installed.
9:12:43 PM: Bundled gems are installed into `/opt/build/cache/bundle`
9:12:43 PM: Post-install message from i18n:
9:12:43 PM: HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
9:12:43 PM: But that may break your application.
9:12:43 PM: If you are upgrading your Rails application from an older version of Rails:
9:12:43 PM: Please check your Rails app for 'config.i18n.fallbacks = true'.
9:12:43 PM: If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be'config.i18n.fallbacks = [I18n.default_locale]'.
9:12:43 PM: If not, fallbacks will be broken in your app by I18n 1.1.x.
9:12:43 PM: If you are starting a NEW Rails application, you can ignore this notice.
9:12:43 PM: For more info see:
9:12:43 PM: https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
9:12:43 PM: Post-install message from html-pipeline:
9:12:43 PM: -------------------------------------------------
9:12:43 PM: Thank you for installing html-pipeline!
9:12:43 PM: You must bundle Filter gem dependencies.
9:12:43 PM: See html-pipeline README.md for more details.
9:12:43 PM: https://github.com/jch/html-pipeline#dependencies
9:12:43 PM: -------------------------------------------------
9:12:43 PM: Gem bundle installed
9:12:43 PM: Started restoring cached node modules
9:12:43 PM: Finished restoring cached node modules
9:12:43 PM: Installing NPM modules using NPM version 6.14.4
9:12:48 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/core-js
9:12:48 PM: > node -e "try{require('./postinstall')}catch(e){}"
9:12:48 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
9:12:48 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
9:12:48 PM: added 263 packages from 155 contributors and audited 333 packages in 4.81s
9:12:49 PM: 12 packages are looking for funding
9:12:49 PM:   run `npm fund` for details
9:12:49 PM: found 20 low severity vulnerabilities
9:12:49 PM:   run `npm audit fix` to fix them, or `npm audit` for details
9:12:49 PM: NPM modules installed
9:12:49 PM: Started restoring cached go cache
9:12:49 PM: Finished restoring cached go cache
9:12:49 PM: go version go1.14.4 linux/amd64
9:12:49 PM: go version go1.14.4 linux/amd64
9:12:49 PM: Installing missing commands
9:12:49 PM: Verify run directory
9:12:50 PM: ​
9:12:50 PM: ────────────────────────────────────────────────────────────────
9:12:50 PM:   Netlify Build                                                 
9:12:50 PM: ────────────────────────────────────────────────────────────────
9:12:50 PM: ​
9:12:50 PM: ❯ Version
9:12:50 PM:   @netlify/build 8.0.5
9:12:50 PM: ​
9:12:50 PM: ❯ Flags
9:12:50 PM:   deployId: 6004ed5e51163928b2e7b599
9:12:50 PM:   mode: buildbot
9:12:50 PM: ​
9:12:50 PM: ❯ Current directory
9:12:50 PM:   /opt/build/repo
9:12:50 PM: ​
9:12:50 PM: ❯ Config file
9:12:50 PM:   No config file was defined: using default values.
9:12:50 PM: ​
9:12:50 PM: ❯ Context
9:12:50 PM:   production
9:12:50 PM: ​
9:12:50 PM: ────────────────────────────────────────────────────────────────
9:12:50 PM:   1. Build command from Netlify app                             
9:12:50 PM: ────────────────────────────────────────────────────────────────
9:12:50 PM: ​
9:12:50 PM: $ jekyll build
9:12:51 PM: Configuration file: /opt/build/repo/_config.yml
9:12:51 PM:             Source: /opt/build/repo
9:12:51 PM:        Destination: /opt/build/repo/_site
9:12:51 PM:  Incremental build: disabled. Enable with --incremental
9:12:51 PM:       Generating...
9:12:51 PM:        Jekyll Feed: Generating feed for posts
9:12:53 PM:                     done in 1.945 seconds.
9:12:53 PM:  Auto-regeneration: disabled. Use --watch to enable.
9:12:53 PM: ​
9:12:53 PM: (build.command completed in 2.7s)
9:12:53 PM: ​
9:12:53 PM: ────────────────────────────────────────────────────────────────
9:12:53 PM:   Netlify Build Complete                                        
9:12:53 PM: ────────────────────────────────────────────────────────────────
9:12:53 PM: ​
9:12:53 PM: (Netlify Build completed in 2.8s)
9:12:53 PM: Caching artifacts
9:12:53 PM: Started saving ruby gems
9:12:53 PM: Finished saving ruby gems
9:12:53 PM: Started saving node modules
9:12:53 PM: Finished saving node modules
9:12:53 PM: Started saving build plugins
9:12:53 PM: Finished saving build plugins
9:12:53 PM: Started saving pip cache
9:12:53 PM: Finished saving pip cache
9:12:53 PM: Started saving emacs cask dependencies
9:12:53 PM: Finished saving emacs cask dependencies
9:12:53 PM: Started saving maven dependencies
9:12:53 PM: Finished saving maven dependencies
9:12:53 PM: Started saving boot dependencies
9:12:53 PM: Finished saving boot dependencies
9:12:53 PM: Started saving rust rustup cache
9:12:53 PM: Finished saving rust rustup cache
9:12:53 PM: Started saving rust cargo bin cache
9:12:53 PM: Finished saving rust cargo bin cache
9:12:53 PM: Started saving go dependencies
9:12:53 PM: Finished saving go dependencies
9:12:56 PM: Build script success
9:12:56 PM: Starting to deploy site from '_site'
9:12:56 PM: Creating deploy tree 
9:12:56 PM: Creating deploy upload records
9:12:56 PM: 57 new files to upload
9:12:56 PM: 0 new functions to upload
9:12:58 PM: Starting post processing
9:12:58 PM: Post processing - HTML
9:13:01 PM: Post processing - header rules
9:13:01 PM: Post processing - redirect rules
9:13:01 PM: Post processing done
9:13:01 PM: Site is live ✨
9:13:23 PM: Finished processing build request in 5m42.346890101s

**Review by dpulitano — APPROVED** [review]

**Comment by shannonmcharg** [comment]
@rentry I'm getting this error when I try to build this branch. 
image

**Comment by rentry** [comment]
@shannonmcharg You could try running what is in the output...

`gem install bundler:2.2.3`
and then
`bundle install`

Although, you'll probably encounter all of this again when your new machine arrives, so you might want to just wait (unless there's something pressing coming up for Maine Ballot).

**Review by shannonmcharg — APPROVED** [review]
Got it to work.

**Pull request merged**
