### PR TITLE
Astro

### PR DESCRIPTION
**Pull request by IHIutch**
This is an enhancement or feature.

## Summary

Updates the site to use Astro instead of Jekyll

## Context

These changes update the site to be faster, more organized, and more "developer"-friendly by using [Astro](https://astro.build/) and [Tailwind CSS](https://tailwindcss.com/)

Closes the following "to-dos":
- #368
- #367 
- #364 
- #363
- #362
- #361 
- #360 
- #359
- #358
- #357
- #356
- #355
- #354
- #353
- #352
- #351

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry Will you please review? I can’t find the place to add a reviewer on my phone.

**Comment by shannonmcharg** [comment]
@inomyabcs Do you also want to review?

**Comment by shannonmcharg** [comment]
@IHIutch Can you please drop the 2 right columns on the local elections page? I couldn't figure out how to do that.

**Comment by IHIutch** [comment]
> @IHIutch Can you please drop the 2 right columns on the local elections page? I couldn't figure out how to do that.

Updated

**Comment by rentry** [comment]
There's a typo with ballotpedia on the local elections page. It would also be nice to have the table search on that page.

The local website is _snappy_...really fast. I personally think it's risky to try to merge this before the election, but I do think it's a better direction long term. I don't have time to review everything, but in general it looks good to me.

**Comment by IHIutch** [comment]
Added the search to the candidates and archive tables

**Comment by rentry** [comment]
The website is currently deployed via GH Pages, and will likely require a GH Actions addition to build the site via npm... @IHIutch 

I'm sure you're considering that, but Jekyll just automatically served it (with the Ruby stack) so that might be a requirement to maintain the build.

**Comment by rentry** [comment]
There is a Netlify build, but that's not production to my knowledge.

**Comment by IHIutch** [comment]
@rentry I think the current site is actually being built in Netlify, I think the github action is legacy from when the site was hosted on GitHub Pages. I did update the `netlify.toml`, so the merge will automatically use the Astro build process.

https://github.com/OpenMaine/maineballot/pull/381/files#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489ed

But otherwise, I think we can handle it all in the Netlify UI once it's all merged

**Comment by shannonmcharg** [comment]
If we aren't 100% sure it will build, I think we should wait until after the election to merge.

**Comment by IHIutch** [comment]
The `netlify.toml` [overrides the configuration](https://docs.netlify.com/configure-builds/file-based-configuration/) in the UI, so we should be good. It's using the same configuration for the `astro` branch.

My point was more that we won't need the `netlify.toml` once we've merged everything because we can go back to using the Netlify UI.

Worst case scenario, the build doesn't work and the Jekyll site stays up. But it's not a complicated fix either way.

**Pull request merged**
