### PR TITLE
Nove 2024 Questions

### PR DESCRIPTION
**Pull request by shannonmcharg**
Adds statewide ballot questions.

### CODE REVIEW

**Review by inomyabcs — APPROVED** [review]
Question 1 and 2 markup doesn't appear to have errors from my viewpoint.

**Comment by shannonmcharg** [comment]
@inomyabcs That's good because GitHub desktop is telling me I'm not connected to the internet, so I can't see my updates.

**Comment by shannonmcharg** [comment]
@inomyabcs The rest of the questions are now in. Can you take a look and let me know if it looks good to merge?

**Comment by inomyabcs** [comment]
Agree. Thanks for doing a better job of reading through those then I did. I was going to miss a lot of little errors.

**Pull request merged**
