### PR TITLE
Updates local election info for York, Washington, and Waldo counties

### PR DESCRIPTION
**Pull request by shannonmcharg**
Updates June election info for York, Washington, and Waldo counties.

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@dpulitano How do I get a preview link?

**Review by caitlinpmarshall — APPROVED** [review]
Looks good to me! First opportunity to do a review here, so thank you for that.  I presume for this csv, it's mostly a proofreading check?

**Review by relspeedwagon — APPROVED** [review]

**Comment by dpulitano** [comment]
Hey @shannonmcharg , really sorry for the delay - I just fixed it. You should start seeing the branch previews now -- i.e. see this test PR I just opened here https://github.com/OpenMaine/maineballot/pull/216

It was my bad. It got disabled in Netlify because of a "post-deploy hook" I tried to set up so that deployment notifications would show up in the Slack channel. Since those notifications failed a few times in a row, all of the notifications got disabled, including the branch previews. I just removed that and now it's working. Let me know if you see any other issues again--thanks

**Comment by shannonmcharg** [comment]
@dpulitano Do I just go into Netlify to get the preview link after submitting a PR or is there a standard format for links?

**Comment by dpulitano** [comment]
On any new GitHub PRs, there should be a link that comes at the bottom...
it will grayed out for 5 minutes or so after first submitting. Let me know
if you have any issues and I can help!

**Pull request merged**
