### PR TITLE
Localarchive

### PR DESCRIPTION
**Pull request by inomyabcs**
This is an enhancement or feature.

## Summary

Added two perl scripts to slice the local.csv file in the _data directory.
Created localarchive.csv to move the Nov 19 data.
Updated local.md in _pages for inputting the July 2020 election date for the ballot issues.

## Context

Issue #79

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@inomyabcs Thanks for starting this!  We should probably put the election date on the archive file, since we'll end up with one for each election.

@rentry Is there a way to get the archived file to be linked from the archive page?  I'm not sure how to get it in there with the for loop.

**Comment by inomyabcs** [comment]
Ok, I was thinking of one file to hold future archives as well by adding more columns. Didn't want to clutter up the directory.

**Comment by rentry** [comment]
It would be easier to auto-archive these local election files if they contained front matter, but options are limited with data files. We could create a layout and/or include for each local election year, and connect the front matter to respective data files, but that would require quite a bit of manual work. We could create a markdown file for each election (possibly in a collection 👇) and generate a page for each local election.

We could also just pull the static file from `_site` into a new local archive directory and link to it. The problem with that method is that the page wouldn't reflect any changes to header, footer, new elections, etc., over time.

[Collections](https://jekyllrb.com/docs/collections/) could be useful here, but I think we still need some form of templating to use them (not just csv files).  

I'm not adept at perl, so I can't really evaluate this pull request, but automating the process would be ideal.

**Comment by shannonmcharg** [comment]
@inomyabcs  Do we still want the part of this that changes the local page to July?

**Comment by inomyabcs** [comment]
@shannonmcharg I would say no at the moment. Let's see we are on Wednesday?

**Comment by shannonmcharg** [comment]
@inomyabcs Sounds good.

**Pull request closed without merging**
