### PR TITLE
Adds gemfile back to attempt Netlify build fix (again)

### PR DESCRIPTION
**Pull request by rentry**
Builds are failing (again) in the Netlify preview.

This PR attempts to fix those builds by adding back Gemfile dependency management.

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry I get these errors when I attempt to build the branch in this PR.
image

**Comment by rentry** [comment]
Try running

bundle exec jekyll serve

**Comment by shannonmcharg** [comment]
I get this error when I do that.
image

In case the highlighted version is easier to read:
image

**Comment by rentry** [comment]
You probably need to run `bundle install` and then `bundle exec jekyll serve`.

Cross your fingers...this is where my dev environment broke and had to be reassembled.

We could delay this Netlify stuff until after the election, so you can get on with that, if you prefer.

**Comment by shannonmcharg** [comment]
Let’s put it off until after the election.

**Comment by rentry** [comment]
Sounds good.

**Pull request closed without merging**
