### PR TITLE
Enable Netlify deployments

### PR DESCRIPTION
**Pull request by dpulitano**
This is an enhancement or feature.

## Summary

This adds a Gemfile (and Gemfile.lock file) to enable Netlify builds.

To get this set up on Netlify, you need to just use `jekyll build` as the build command and `_site` as the site directory

 According to a few sources online, we should need a Gemfile with the jekyll plugins that are in `_config.yml` added to it:
- https://forestry.io/docs/guides/developing-with-jekyll/plugins/#:~:text=Installing%20Plugins,-Forestry%20supports%20all&text=Installation%20generally%20has%20three%20steps,one%20in%20your%20project%20root.&text=You%20must%20also%20add%20the,array%20in%20your%20Jekyll%20_config.
- https://jekyllrb.com/docs/ruby-101/#gems

I had to remove the *.gem line in .gitignore in order to save the Gemfile.

And according to this - https://bundler.io/v1.7/rationale.html#checking-your-code-into-version-control, checking in the Gemfile.lock in with the Gemfile is a good practice because it "locks in" the version of Jekyll and other gems, and makes sure that the same versions of them are used each time the site is built. So I removed Gemfile.lock as well from the .gitignore and include the Gemfile.lock that was generated.

Here is the code running from this branch on Netlify:
https://upbeat-wescoff-f0d870.netlify.app/

Once Ruby is installed locally, you can run `jekyll serve` to launch the website on localhost:4000.

## Context

This PR is for https://github.com/OpenMaine/maineballot/issues/165

### CODE REVIEW

**Comment by dpulitano** [comment]
By the way, an additional test case I did was to edit a scss file in the _sass folder and ensured that the build accounted for the change.

Tested increasing the line spacing from 1.5 to 3.5 in base.scss -  https://github.com/dpulitano/maineballot/commit/65b071937daa14a4deb56cb90b45ab1cb969df1c
Resulted in a netlify deployment with the larger line spacing: https://5f71466ee4e91d00097ad74d--upbeat-wescoff-f0d870.netlify.app/

**Comment by shannonmcharg** [comment]
I added @rentry as a reviewer on the because I don't know what to look for.

**Comment by rentry** [comment]
@dpulitano Could you change the destination for this PR to `staging`? That way we can merge into staging and pull down your branch for testing before merging to production.

**Comment by shannonmcharg** [comment]
Did this change anything in Master yet?  I'm trying to add the link to the new absentee ballot status tool and the changes aren't showing up when I try to preview locally.

**Comment by shannonmcharg** [comment]
Nevermind, it's working now.

**Comment by dpulitano** [comment]
Hey @rentry - I tried rebasing my branch with origin/staging but I see there's a lot of stuff in there that isn't in master and it hasn't been updated since January (i.e. in staging, there is a Gemfile and gemspec but there is none in master -- not sure if that's needed to be there or not)... would it make more sense for you to just pull down this branch for testing? Or maybe I can merge into a "new" branch in this repo for you to pull down? Happy to merge into staging too but just not sure how to proceed with the build files in there -- can I overwrite them all?

Glad that I didn't break anything...yet @shannonmcharg 😄

**Comment by rentry** [comment]
@dpulitano Apologies...I forgot about the older junk in `staging`. You can wipe that out or open a new branch, if you want. I thought it might be easier to pull it into the repo and work on it rather than pull from yours, but I can go either way.

**Comment by dpulitano** [comment]
OK no problem - I wiped out the existing Gemfile and gemspec in staging with my merged PR so it matches the files in master @rentry. I was able to deploy locally fine with the same commands - just the content is different in there.

Feel free to reach out on Slack if you have more questions (or here)

**Pull request merged**
