### PR TITLE
Merge files to enable Netlify deployments

### PR DESCRIPTION
**Pull request by dpulitano**
This is an enhancement or feature. 

## Summary

This adds a Gemfile (and Gemfile.lock file) to enable Netlify builds.

To get this set up on Netlify, you need to just use `jekyll build` as the build command and `_site` as the site directory

According to a few sources online, we should need a Gemfile with the jekyll plugins that are in `_config.yml` added to it:

- https://forestry.io/docs/guides/developing-with-jekyll/plugins/#:~:text=Installing%20Plugins,-Forestry%20supports%20all&text=Installation%20generally%20has%20three%20steps,one%20in%20your%20project%20root.&text=You%20must%20also%20add%20the,array%20in%20your%20Jekyll%20_config.
- https://jekyllrb.com/docs/ruby-101/#gems

I had to remove the *.gem line in .gitignore in order to save the Gemfile.

And according to this - https://bundler.io/v1.7/rationale.html#checking-your-code-into-version-control, checking in the Gemfile.lock in with the Gemfile is a good practice because it "locks in" the version of Jekyll and other gems, and makes sure that the same versions of them are used each time the site is built. So I removed Gemfile.lock as well from the .gitignore and include the Gemfile.lock that was generated.

Here is the code running from this branch on Netlify:
https://upbeat-wescoff-f0d870.netlify.app/

Once Ruby is installed locally, you can run jekyll serve to launch the website on localhost:4000.

## Context

This PR is for #165

### CODE REVIEW

**Comment by dpulitano** [comment]
OK for me to merge this, @rentry ?

**Comment by rentry** [comment]
@dpulitano Yeah, since @shannonmcharg got it running locally, I think we're good to go! Thank you.

**Comment by rentry** [comment]
The question now is whether to use Netlify for production, or stick with GH Pages for production and use Netlify for branch previews.

**Comment by rentry** [comment]
We should probably revisit that one after November.

**Comment by dpulitano** [comment]
Cool. Sounds good. Nothing stops us from deploying on Netlify and GH Pages at the same time, so we can always set it up on Netlify and take advantage of the branch builds there but still use GH Pages for Production. Whatever we want :)

**Comment by shannonmcharg** [comment]
So, now how do we get preview links for PRs?

**Comment by dpulitano** [comment]
I think there should just some simple Netlify setup that has to be done to set up the build. And then following these instructions should link the PR preview URLs into the GitHub PRs (I didn't know about this -- this is really cool!) - https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

I'm happy to help with the Netlify setup if you'd like ... does OpenMaine have a Netlify account already?

**Comment by shannonmcharg** [comment]
OpenMaine doesn't have a Netlify account.  I just put it under my personal email last time.  

@elburnett @congdon Thoughts on using the hello@openmaine.org account so it's not tied to an individual?

**Comment by congdon** [comment]
I don't know what Netlify is, nor how many emails this can be expected to generate. We could certainly create another gsuite account.... but is someone going to actually read it?

**Comment by shannonmcharg** [comment]
Netlify is a service that will allow us to generate previews for nondevelopers to be able to review things before they go live.  If we create another email address it could just be for creating accounts for things we don’t want tied to an individual and wouldn’t need to be checked regularly.

**Comment by congdon** [comment]
Hmmm, it seems really a poor idea if people aren't even going to forward the email to an account they actually check regularly. That seems to be what often happens with the other gsuite email accounts.

But I hear you, about not wanting to sign up with an individual's email address.

Do you know how many emails this is expected to generate? In what situations will there be an email?

**Comment by shannonmcharg** [comment]
I have no idea how many emails it will generate.  @dpulitano Do you know?

**Comment by dpulitano** [comment]
I think minimal emails. I opened an account with my personal email in February and have gotten only a few emails from them since. I only received emails for things like adding users to view the dashboard without having the main password or having to reset the password

**Comment by congdon** [comment]
Thanks, dpulitano!

So those are emails that need a timely response. Is it going to be you who fields them, @shannonmcharg?  (There still needs to be someone identified who's responsible, even if the email address is somewhat anonymized.)

**Comment by shannonmcharg** [comment]
Sure

**Comment by dpulitano** [comment]
No problem, Clare. And thanks, @shannonmcharg - maybe we can coordinate on Slack how we can set up the Netlify PR previews? I hope this will primarily be a one-time set up then ideally everything just shows up in GitHub going forward

**Comment by congdon** [comment]
Thanks, both of you. I'll work with Shannon to get her set up on the hello@openmaine.org email alias.

**Pull request merged**
