### PR TITLE
Updates election date

### PR DESCRIPTION
**Pull request by shannonmcharg**
Updates the site for the November election.

[Preview](https://deploy-preview-242--awesome-lamarr-6d076d.netlify.app/)

- Updates election date.
- Archives June local election page.
- Adds November state-wide questions.

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry Question 1 references are doing something wonky and I don't understand why.

**Review by relspeedwagon — CHANGES_REQUESTED** [review]
Only thing I saw would be to double check a few small things in the ref questions before merging

**Review by relspeedwagon — APPROVED** [review]
I guess I didn't need to be so official with my "request for changes" before, lol!  Looks good :)

**Comment by shannonmcharg** [comment]
@relspeedwagon Thanks for reviewing!

**Comment by rentry** [comment]
@shannonmcharg Your reference issues should be fixed. Looked to be a markdown link bracket breaking onto a new line. Should be good to go!

**Pull request merged**
