### PR TITLE
Adds changes that fell off the truck

### PR DESCRIPTION
**Pull request by rentry**
Are these all the changes missing, @shannonmcharg?

### CODE REVIEW

**Comment by shannonmcharg** [comment]
Yes, it's all of them.  Can I edit this branch to make additional changes or should I create a new one after merging?

**Comment by rentry** [comment]
Feel free to add them here, @shannonmcharg.

**Comment by rentry** [comment]
@andyalmandhunter and @shannonmcharg My reset to revert the commit of `_site` also wiped out some of Shannon's changes.

@shannonmcharg Try deleting your `_site` folder from the branch, make the changes again, and recommit.

Apologies for all the hiccups with this one.

**Comment by shannonmcharg** [comment]
@rentry Did that fix it?

**Comment by rentry** [comment]
I think it's good to go, @shannonmcharg. This should add your fixes and remove the `_site` directory.

**Pull request merged**
