### PR TITLE
Adds new bond question

### LINKED ISSUE #18: Q1: An Act To Authorize a General Fund Bond Issue To Improve Highways, Bridges and Multimodal Facilities
There's a new bond question that we need to add to the website.

# Question title
Transportation

# Description (will display on homepage)
This measure would allow the state to borrow $105 million for transportation improvements.

# The gist
Passing this question would allow the state to borrow $105 million, matched by $137 million in federal funds, for transportation improvements. This is the third of 3 consecutive years of transportation bonds that will fill a shortfall in the highway fund.

# Ballot question (exact text of the question)
"Do you favor a $105,000,000 bond issue to build or improve roads, bridges, railroads, airports, transit and ports and make other transportation investments, to be used to match an estimated $137,000,000 in federal and other funds?"

# Yes means
I am in favor of issuing the $105 million bond to address infrastructure improvements.

# No means
I do not want Maine to borrow $105 million to address infrastructure improvements.

# Tell me more
Passing this question would allow the State of Maine to borrow $105 million for a variety of infrastructure improvements, including roads, bridges, railroads, airports, transit and ports.[^3]

This is a **bond issue** -- if voters approve the bond, it means that the State of Maine is allowed to borrow money for the project described in the ballot question and has to pay it back over 10 years. [Learn more about how bonds work](/bonds).

# Follow the money
Principal: $105,000,000
<br>Interest: $28,875,000 (assumes 5.0% over 10 years)
<br>Total cost:  $133,875,000[^3]

The money will be used to
* $85 million for highways and bridges [^3]
* $15 million for projects that “preserve public safety or otherwise have demonstrated high transportation value” for things like  ports, railroads, airports, bicycle, and walking trails[^3]
* $4 million to fund a Department of Environmental Protection grant program for upgrading fish and wildlife habitats[^3]
* $1 million for improving a wharf at the Gulf of Maine Research Institute[^3]

The money will be coming from
* $105 million bond issued by the state  and paid back through the budget and taxes over 10 years.[^3]  
* $137 million in matching funds from federal and local governments[^3]  
  - The federal government will match funds for highway and bridge projects at a ratio of 1.1 federal dollar to 1 state dollar.[^3]
  - Municipalities will be required to match 50% or more of project costs[^3].

# Pros
The primary arguments for this referendum are:
* Maine's roads and infrastructure are deteriorating.
* Makes up for some of the shortfall in gas taxes from fuel-efficient vehicles that has left the funds for highway repairs insufficient.
* Issuing the bond opens up matching funds.
* Interest rates are currently low, making it a good time to invest.[^3]

# Cons
The primary arguments against this referendum are:
* Maine already has $653,433,911 in outstanding bond debt that this will add to and it could lead to increased taxes.[^3]

# Who cares
Nobody has registered support or opposition to this measure.

# Further reading
[Full text](https://www1.maine.gov/sos/cec/elec/upcoming/pdf/plchap532.pdf)
[Ballotpedia article](https://ballotpedia.org/Maine_Transportation_Infrastructure_Bond_Issue_(2019))

# References
_Put the number in brackets above to indicate a footnote to a reference._
1. Maine State Legislature. [H.P. 1049 - L.D. 1437](https://www1.maine.gov/sos/cec/elec/upcoming/pdf/ld1437.pdf). Accessed September 16, 2019.
2. Ballotpedia State Desk. [Maine Transportation Infrastructure Bond Issue (2019)](https://ballotpedia.org/Maine_Transportation_Infrastructure_Bond_Issue_(2019)). Ballotpedia. Accessed September 16, 2019.
3. Dunlap, Matthew. [Maine Citizen’s Guide to the Referendum Election](https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide19.pdf). Accessed September 16, 2019.

# Image
We can use the same image we've used for other transportation bond questions.
/assets/img/2018_11/Question3Transportation.jpg

# Tags
Bond
Transportation

# Election date
November 5, 2019

### PR DESCRIPTION
**Pull request by shannonmcharg**
Fixes #18

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry This is hiding the second item listed in the references. Any idea why?

**Comment by rentry** [comment]
Looks like a space is missing on the second reference (after the colon).
You could try that.

```
[^1]: Maine State Legislature. [H.P. 1049 - L.D. 1437](
https://www.maine.gov/sos/cec/elec/upcoming/pdf/ld1437.pdf). Accessed
August 30, 2019.
[^2]:Ballotpedia State Desk. [Maine Allow for Alternative Initiative
Signatures for Persons with Disabilities Amendment (2019)](
https://ballotpedia.org/Maine_Allow_for_Alternative_Initiative_Signatures_for_Persons_with_Disabilities_Amendment_(2019)).
Ballotpedia. Accessed August 30, 2019.
[^3]: Byrne, Ryan. [Maine to vote on a ballot measure to allow persons with
physical disabilities to sign initiative petitions using an alternative
signature](
https://news.ballotpedia.org/2019/06/22/voters-in-maine-will-decide-a-constitutional-amendment-to-allow-persons-with-physical-disabilities-to-sign-ballot-measure-petitions-using-an/).
Ballotpedia. Accessed August 30, 2019.
[^4]: Dunlap, Matthew. [Maine Citizen’s Guide to the Referendum Election](
https://www.maine.gov/sos/cec/elec/upcoming/pdf/citizensguide19.pdf).
Accessed September 16, 2019.
```

**Comment by shannonmcharg** [comment]
@rentry The spaces didn't fix it and it's hiding references on both questions.

**Comment by congdon** [comment]
I don't know how to run this locally on my machine. Are there instructions somewhere?

**Comment by shannonmcharg** [comment]
@congdon The same way you did it for the Jekyll version of the OpenMaine site.

**Comment by shannonmcharg** [comment]
@rentry I think it may be hiding references that don't have any footnotes that refer to them from the content.

**Comment by rentry** [comment]
That makes sense. So you want to retain the reference, but you don't have a
footnote in the markdown body to link to it? You may then want to remove
the footnote syntax in references and just list it without the ^2 syntax,
since it isn't, in this case, a footnote.

**Comment by shannonmcharg** [comment]
@rentry Sometimes I've read something, so it's a reference, but I'm not directly citing, so it doesn't end up with any footnotes. 

It messes up the format if I just take out the number:
image

**Comment by rentry** [comment]
Yes, and in that case you might be able to use HTML to restyle it.

<li><p>Reference that isn't a footnote</p></li>

If that doesn't work (because it falls out of the footnote-classed div),
you could add the body footnote to the Ballotpedia link under "Further
reading".

**Pull request merged**
