### PR TITLE
Test PR to test Netlify integration

### PR DESCRIPTION
**Pull request by dpulitano**

### CODE REVIEW

**Comment by rentry** [comment]
The one concern I have about moving the production environment to Netlify is that it will be tied to one person's account. The advantage of keeping prod in GitHub Pages, and still using Netlify for branch previews, is that the production isn't tied to a single account. I also think GitHub Pages is less temperamental about dependencies than is Netlify.

That said, Netlify is more intuitive, with more build feedback and checks. I think we should at the very least use Netlify for branch builds and previews, but I defer to @shannonmcharg on the bigger prod question.

**Comment by shannonmcharg** [comment]
@rentry I created a Netlify account with the hellp@openmaine.org email address, which several people have access to and this PR should get it setup in that account.

**Review by rentry — APPROVED** [review]

**Comment by shannonmcharg** [comment]
I have no idea what it means to have prod in one vs. the other.  My mail goal with Netlify is getting preview links, so non-developers can review changes before pushing.

**Comment by rentry** [comment]
@shannonmcharg Having production in Netlify will require making changes to your DNS records to point the domain to Netlify instead of GH Pages, but other than that, it shouldn't be much different.

**Comment by shannonmcharg** [comment]
I'm good with whatever @rentry and @dpulitano think is best.  Just let me know what you need me to do on my end.

**Comment by dpulitano** [comment]
Hi @shannonmcharg, to do this, you must add the following record to the DNS (including the trailing period):
`www CNAME awesome-lamarr-6d076d.netlify.app.`

Again, I'm pretty sure you won't experience downtime, but not positive :-| -- if there's an hour of day where you will see the least amount of traffic, I'd recommend changing it then

Let me know if you have any questions.. once it's finished I can verify all is well in Netlify

**Comment by dpulitano** [comment]
Also, I would recommend to take a copy of the current name server values just in case rolling back is necessary

**Comment by dpulitano** [comment]
Closing since we got Netlify setup completely.

**Pull request closed without merging**
