### PR TITLE
Adds page for Nov 2019 ballot question

### PR DESCRIPTION
**Pull request by shannonmcharg**
Adds content for November 2019 ballot question per #10 and adds current election date per #13.

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry I got a page put in for the one question on the November ballot, but I couldn't figure out how to get it to display in the list of questions on the homepage.

**Comment by rentry** [comment]
Very weird. The keys match, so I'm not sure what's going on. I'll look into
it.

**Comment by rentry** [comment]
There's something wrong with the markdown formatting on the new file, @shannonmcharg. I changed the `election` and `categories` of a previous ballot question, and it shows up, so there's something breaking in the new file preventing it from building. Unfortunately, there's no error, so it's difficult to know what it is. I'll see if I can track it down.

**Comment by rentry** [comment]
Okay @shannonmcharg, I figured it out. Jekyll blocks the rendering of any blog posts with future dates in the filename. This kind of makes sense (I guess), since one might want to prepare a post for a future date, but not publish it at the time of writing (although `_drafts` exists for this purpose, so it's still a little murky).

Anyway, I added a setting in `_config.yml` to allow rendering of posts with future dates in the filenames. If you pull it down, it should work just fine.

**Comment by shannonmcharg** [comment]
@rentry That fixed it. Thanks!

**Pull request merged**
