### PR TITLE
Fix footnote link and add jekyll cache to gitignore

### PR DESCRIPTION
**Pull request by rentry**
- Fixes link format in footnote
footnote between brackets and parentheses breaking markdown link format

- Adds `.jekyll-cache` to `.gitignore`

### CODE REVIEW

**Comment by shannonmcharg** [comment]
Just noticed this unfixed the misspellings in the footnote.

**Comment by rentry** [comment]
That's odd, @shannonmcharg. I pulled `master` and branched off it, so it should have had the change with it.

Weird.

**Comment by rentry** [comment]
The `.gitignore` file isn't here, either, which is strange.

**Comment by shannonmcharg** [comment]
@rentry Do we want to merge this branch or do things need to be fixed first?

**Comment by rentry** [comment]
Should be fine to merge, @shannonmcharg, since it only contains the link fix.

**Pull request merged**
