### PR TITLE
Updates local election info

### LINKED ISSUE #101: Add ability to link to local sample ballot or warrant from local elections page
I added a column to the Google spreadsheet for this.  We need to add logic for it to show on the page.

https://docs.google.com/spreadsheets/d/1dk58MD0qBAM37BDOZwKIz10hp5AARAIX8u_qvuDnYaI/edit#gid=0

### PR DESCRIPTION
**Pull request by shannonmcharg**
Fixes #101 
- Updates dates for some local elections
- Adds column with sample ballot or warrant

### CODE REVIEW

**Comment by shannonmcharg** [comment]
Durham has a link to a pdf in a folder within the local_elections folder, but I can't figure out the right path to put in there.  @rentry Can you please help?

**Comment by rentry** [comment]
This should be fixed now. The `_data` folder only compiles `csv` and `json` files, and it doesn't really know how to handle a `pdf`. So this moves the pdf to a new `docs` directory in `assets`, and backs out the relative url one level:

`../assets/docs/2020-07-14_ballots/Durham.pdf`

You probably want to change the link location in the source spreadsheet so it isn't overwritten if you update!

**Comment by shannonmcharg** [comment]
@rentry I updated the link in the csv and it's still saying the file doesn't exist.

**Comment by rentry** [comment]
Did you `git pull` on the branch @shannonmcharg?

**Comment by shannonmcharg** [comment]
Not in the command line, but yes, I pulled from origin.

**Comment by rentry** [comment]
Huh, it's working for me locally.

In your file system locally do you see `assets/docs/2020-07-14_ballots/Durham.pdf`?

**Comment by shannonmcharg** [comment]
Yes

**Comment by shannonmcharg** [comment]
It's working now!

**Comment by rentry** [comment]
Did you refresh `/local`? What is the link path for Sample Ballot?

**Comment by shannonmcharg** [comment]
I must have needed to refresh or something.

**Pull request merged**
