### PR TITLE
Issue 176

### PR DESCRIPTION
**Pull request by inomyabcs**
Content about properly filling out an absentee ballot. Not integrated with main website.

This is an enhancement or feature. 

## Summary

Adds absentee ballot instructions and informs on common rejections of absentee ballots.

## Context

Fulfills issue 176.

### CODE REVIEW

**Comment by inomyabcs** [comment]
This is content only and hasn't been properly integrated with the system we are using. Would need someone to integrate the content and check the image links since they are relative to the main tree.

**Comment by shannonmcharg** [comment]
@inomyabcs Thanks for starting this! I don't have time to get this integrated into the site right now, so I'll make an issue for it that someone might pick up.
Page preview: https://deploy-preview-317--awesome-lamarr-6d076d.netlify.app/ballotfill.html

**Comment by shannonmcharg** [comment]
@rentry Can you please help with this? There's a new page that needed the styling of the site added to it. I added front matter to give it a template, but it's sizing weirdly and it broke all the icons that were in the page.

**Comment by rentry** [comment]
@shannonmcharg This page will be difficult to integrate, since it has around 235 lines of inline CSS, some of which rewrite important styling for the layout of the website. For example, it imposes styling on the `html`, `body`, and headings, which (because of the specificity of being page-level) replace global styling on the page. It also rewrites mobile views and breakpoints. As-is, we won't be able to integrate it.

We would have to go through it line-by-line to remove some CSS, pull the in-line CSS for the step chart into the stylesheet, etc., but if we do that, it will still take some effort to make sure that it looks like it's intended to. 

I don't have time to do all of that for a while, but I can look into it later if I find a few hours. In the meantime, if you want to add it, I would recommend doing so as a bespoke page. With all that inline styling, it current assumes itself as an independent page.

**Comment by shannonmcharg** [comment]
@rentry Thanks for taking a look! We'll table this page for later.

**Comment by inomyabcs** [comment]
I have modified the ballot page using the USWDS page recommended by @rentry. The deploy preview shows that it isn't breaking the site layout. There are some little cosmetic changes that will need to be performed later (the blue line is off centered and the text sizing in each section needs adjusting).

**Comment by rentry** [comment]
Nice @inomyabcs! I added a few tweaks via #331! It looks great, and retains 100% accessibility 👍

**Comment by shannonmcharg** [comment]
The preview on this one looks great!

**Comment by shannonmcharg** [comment]
Is all that's left to do on this to add a link to the page from the How to Vote in Maine page?

**Comment by inomyabcs** [comment]
Looks like it. Everyone seems happy with the page.

**Comment by shannonmcharg** [comment]
I added a link under the Vote by Mail section. @rentry I probably have the wrong verb construction, if you want to tweak it.

**Comment by rentry** [comment]
There is one more issue to look into with this one, which I should have caught and I'm surprised the accessibility checker didn't catch.

The page doesn't currently have an `h1` or `h2`, skipping to `h3` and `h4`s for the list items.

A headings map of the page with the h3 highlighted in red

Ideally, it would have an `h1` page title, then proceed to `h2` and so on.

**Comment by rentry** [comment]
I'll push up some heading tweaks in a bit.

**Review by shannonmcharg — APPROVED** [review]

**Comment by shannonmcharg** [comment]
@inomyabcs It won't let me add you a reviewer, since it's your pull request. If everything looks good to you, feel free to merge.

**Comment by inomyabcs** [comment]
Thank you all for your assistance.

**Pull request merged**
