### PR TITLE
Make search aware of counties

### PR DESCRIPTION
**Pull request by andyalmandhunter**
## Summary

#53 added a search input to the local election pages.  This updates the search logic to match the associated county if you search for a town, and match all associated towns if you search for a county.

rec0

Note: to simplify some of the logic added here it made sense to me to fill in the 'County' column in the local elections CSV.  I know that file's being edited quite a bit at the moment and this might cause conflicts with in-flight work.  If any conflicts come up I'd be happy to help resolve them.

### CODE REVIEW

**Comment by shannonmcharg** [comment]
It should be fine to have county in the spreadsheet.  We’re using a Google Sheet to do the populating and that has a county column for sorting.  I can add that column in when copying to the csv.

**Comment by shannonmcharg** [comment]
@andyalmandhunter I got a page build error when I attempted to merge this PR.
image

**Comment by andyalmandhunter** [comment]
Ugh, sorry, I'll look into that.

**Comment by andyalmandhunter** [comment]
🤦‍♂ As it turns out, github pages won't build custom plugins.  Which they sort of say [here](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins), but they could be a little more clear about it. 😐  (update) Actually the Jekyll docs mention it [too](https://jekyllrb.com/docs/plugins/installation/).  Oops.

I'll submit a PR to revert these changes.  There are other ways to do this.  I'll work on it when I have some time, but search already works pretty well, I think.  Getting the search terms into Google Analytics seems more important.

**Comment by shannonmcharg** [comment]
Sounds good.

**Pull request merged**
