### PR TITLE
[WIP] Adds draft local elections page

### PR DESCRIPTION
**Pull request by shannonmcharg**
I added a placeholder local elections page that we can use to start adding links to county and city/town websites.

A few things that need to be figured out:
- [ ] I was only able to find lists of cities and towns, not sure if there are other levels like township that need to be added.
- [ ] The image isn't sizing to the thumbnail.  Not sure how to do that.
- [ ] I'd like this to always be the last item in the list on the homepage, but I don't know how to force rank that list.

### CODE REVIEW

**Comment by rentry** [comment]
In my opinion, local elections don't fit neatly with the statewide ballot questions, and should probably have a different structural solution.

That could involve creating the local elections pages in the `_pages` directory instead, and then adding a link to the page on the homepage or nav menu, separate from the `_posts` directory and display. You could separate the homepage into separate state and local sections, and use similar logic to publish the appropriate (current) local election page(s).

**Comment by shannonmcharg** [comment]
@rentry This is meant to be an MVP that just has links to websites for local elections because we haven’t found anyone who even has that. We won’t know the extent of the questions for local elections until we get the list compiled, but I’m guessing we won’t have bandwidth for pages for all of them.  Would it be better as a link that’s not part of the thumbnails?

**Comment by rentry** [comment]
I wasn't suggesting pages for each, just a landing page for local elections. My suggestion is to create a page located in the `_pages` directory (instead of `_posts`). You can then add a link anywhere you want.

Assets in the `_posts` directory behave differently than those in `_pages`, at least how we have it set up now. My expectation is that you probably don't want the local election page to behave in the same way as the ballot question pages. If that's the case, you can manage it as a page in the `_pages` directory and then link it wherever you want (if successful at populating the content).

Just suggestions! 👍

**Comment by shannonmcharg** [comment]
@rentry Good point about the behavior of the posts.  I'll figure out a better place to put it.

**Comment by shannonmcharg** [comment]
@rentry I moved the local elections page out of the posts, but the only way I could get the header and footer to show up on the page was to use the posts layout. I tried copying the posts layout to create a new layout, but the header and footer when away when I did that.  How do I get those to show up on a new layout?

**Comment by shannonmcharg** [comment]
@rentry I changed it to the archive layout that is also used on the bonds page and that works.

**Comment by shannonmcharg** [comment]
I'm going to go ahead and merge this now that county and city websites are all in.  I'll create a new PR for adding links to additional towns and townships.

**Pull request merged**
