### PR TITLE
Homepage updated design #131

### PR DESCRIPTION
**Pull request by curtisk**
Initial pass at new homepage layout/structure, ran under local Jekyll with MM to test

#131

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@jenniferthibault Do you want to review?  It wouldn't let me add you as a reviewer, since you don't appear to be in the OpenMaine org.  I sent you an invite to join the org.

**Comment by shannonmcharg** [comment]
@curtisk This is great!  I'm thinking we should probably add links to the absentee ballot request form and municipal clerk's office listings from the homepage.  Links are on the live site right now: https://maineballot.org/

**Comment by shannonmcharg** [comment]
Since we don't have preview links, this is what the homepage looks like.
image

And the How to Vote in Maine page.
image

**Comment by shannonmcharg** [comment]
We also need to figure out where to put credit for the icons.  We do have an image credits section in the ReadMe that I used for one image that required credit.

**Comment by curtisk** [comment]
good point, would it make sense to have an "About" page that would encompass image credits as well as the narrative/overview in the footer of the site? Those feet are getting large!

**Comment by mcharg** [comment]
@curtisk good idea!

**Comment by curtisk** [comment]
adding "About" page, nav, footer pruning and links to "vote by mail" and "early voting" areas

**Comment by shannonmcharg** [comment]
@curtisk I can tell you made changes from the change log, but when I pull the branch they're not showing up locally.  Any idea why?

**Comment by curtisk** [comment]
are you pulling/fetching from the branch or from master?

**Comment by shannonmcharg** [comment]
From the branch.

**Comment by shannonmcharg** [comment]
@curtisk It's acting strangely.  It's not giving me the ability to fetch and only the ability to publish. 
image

**Comment by curtisk** [comment]
not sure why its doing that, is that the github for desktop? Its a pull request with two commits in it...hmmm

**Comment by shannonmcharg** [comment]
I'll just merge it and review it in production.

**Comment by shannonmcharg** [comment]
@curtisk The images broke when I merged.
image

**Comment by shannonmcharg** [comment]
The About page and footer look good.

**Comment by shannonmcharg** [comment]
It looks like it stripped all the styling.

**Comment by curtisk** [comment]
only thing missing are the two new images on homepage, even though they are in merge..... ?

**Comment by curtisk** [comment]
so, it looks like the github hosted server is case sensitive..../assets/img/other versus /assets/img/Other

**Comment by shannonmcharg** [comment]
The blue background was missing, as well, but it appears to be there now.

**Comment by shannonmcharg** [comment]
So it is just the homepage images that are missing now.  It must have just taken a bit for the rest of the styling to catch up.

**Pull request merged**
