### PR TITLE
Abstracts in-page search to apply to other pages

### LINKED ISSUE #113: Add search to candidates page
The list in this PR is daunting.
https://github.com/OpenMaine/maineballot/pull/111

@andyalmandhunter Would you be willing to add a search like you did for the local elections page?

### PR DESCRIPTION
**Pull request by rentry**
Fixes #113 

- Generalizes in-page table search to apply to other pages containing tables
- Adds `_include` with input field
- Creates two new front matter keys:
 - `search_for`: Placeholder text for what user is searching for (e.g., "candidate")
  - `search_column`: Which column in the table you want to search

Notes:
- As built this will search all tables on a given page (with the declared column)
- Front matter column field is required for this to work

### CODE REVIEW

**Comment by shannonmcharg** [comment]
I just merged my other PR to pull into this one because I changed the number of columns in that one.  How do I get Master pulled into this one?

**Comment by rentry** [comment]
You can merge into the current branch.

GitHub interface with Branch selected in menu bar and Merge into current branch highlighted

**Comment by shannonmcharg** [comment]
I got master pulled in.  I tried to get it to search multiple columns (office, district, candidate), but that didn't work.

**Comment by rentry** [comment]
Yeah, this doesn't enable searching multiple columns. It only allows the search to apply to other pages (instead of just town search). Multiple columns is feasible, but this just allows for searching a different column on different pages (that contain a table).

**Pull request merged**
