### PR TITLE
Drafts November 2023

### PR DESCRIPTION
**Pull request by inomyabcs**
Adding skeleton drafts for the November 2023 election

This is an enhancement or feature. 

## Context

This adds 8 skeleton drafts for the upcoming November 2023 election.

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry Do you remember if there's a cap to the number of questions that display on the homepage? We have 8 questions, but only 5 are displaying.

**Comment by rentry** [comment]
@shannonmcharg I think it might be limited in the `_config.yml` file:

```
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
```

You might try bumping that `paginate` value and see if that fixes it!

**Comment by shannonmcharg** [comment]
@rentry Thank you!

**Comment by shannonmcharg** [comment]
@inomyabcs Consider yourself added as a reviewer, since it won't let me add you as a reviewer to your own PR.

**Comment by shannonmcharg** [comment]
I went through all the links to make sure they will look. Will review all the questions again tomorrow with fresh eyes.

**Review by inomyabcs — COMMENTED** [review]
Proposed some spelling and grammatical changes.

**Review by shannonmcharg — APPROVED** [review]

**Comment by shannonmcharg** [comment]
@relspeedwagon Can you be an extra set of eyes before we merge, since we keep finding typos? 

@IHIutch Can you check to see if merging will break your dependabot changes?

**Comment by IHIutch** [comment]
I dont see in here that overwrites my changes

**Pull request merged**
