### PR TITLE
scss tweaks for contrast issues, img presentation role, still more to do

### PR DESCRIPTION
**Pull request by curtisk**
Handling a few WCAG issues towards AA level, will need to discuss changes to minimal mistakes framework/variables, might need to open issues there in particular with contrast in template presets

#66

### CODE REVIEW

**Comment by shannonmcharg** [comment]
@rentry Do we need to care about the netlify deploy failures before merging this PR?

**Comment by shannonmcharg** [comment]
@curtisk This branch is showing the next election as November.  Did you branch from the latest version of Master?
image

**Comment by curtisk** [comment]
yeah, realized what happened, I'll re-submit

**Comment by rentry** [comment]
@shannonmcharg No need to worry about the Netlify alerts. They only indicate that the Netlify build failed, but you're production deployment is GitHub Pages, so it shouldn't affect anything.

**Pull request closed without merging**
