### PR TITLE
Adds sample ballots

### PR DESCRIPTION
**Pull request by shannonmcharg**
Adds sample ballots for Portland, Brunswick, and Gardiner and adds sample watermark to Durham sample ballot.

### CODE REVIEW

**Comment by rentry** [comment]
A few notes:

- It looks like Gardiner is linking to Durham's ballot
- Typo on Brownfield (`Town Meeing Warrant`)
- New Portland linking to Brownfield doc
- None of these docs appear to be accessible to assistive technologies

**Comment by shannonmcharg** [comment]
How do I make the pdf's accessible?

**Comment by rentry** [comment]
Adobe Acrobat Pro (DC? Whatever they call it now) can do it with accessibility tools (text recognition). One of the of the docs appears to be a phone photo, so that one probably won't be viable for text recognition.

**Comment by shannonmcharg** [comment]
I'll create a new issue for that to see if someone has Acrobat Pro and can do that.  I don't have Pro.

**Comment by shannonmcharg** [comment]
@elburnett Do you still have your ballot that you could scan in instead of taking a pic, so we can try to make it accessible?

**Pull request merged**
