### PR TITLE
Integrates ballot fill step chart (❌ please don't merge this)

### PR DESCRIPTION
**Pull request by rentry**
I made an initial attempt to integrate this code into the codebase, but I have several reservations...

First, here's the preview screenshot after integration:

Screenshot of maine ballot, with options for how to vote, archive, how bonds work, the next election, and how to complete absentee ballot process chart with drop shadows and other effects

This will also be available via Netlify preview (this pull request targets `inomyabcs` instead of `master` because it relies on the generated code from that branch).

## Intro

While I appreciate this contribution enough to attempt to integrate it into the codebase, I'm not sure it's sustainable or maintainable to copy code from codepen and try to just plug it in. For instance, this addition to the site (even with the effort to integrate it with global styling) impacts the website's accessibility (and performance, as you can tell)...

## Before this addition (not this page)

Screenshot 2023-08-31 at 8 54 57 PM

## With this addition (this page)

Screenshot 2023-08-31 at 8 55 18 PM

screenshot of the elements marked that don't have sufficient contrast ratio

## Outcome
This seems like a good start, and I would be happy to support this in a more accessible form, such as something similar to the [USWDS process list](https://designsystem.digital.gov/components/process-list/). 

I'm curious, from a user perspective, if this content might be just as effective without all the unnecessary markup and styling...maybe it's just a list of steps? Does it need to have all the drop shadows and animations and images to be effective, because you lose performance (whether or not it loads quickly on a phone or slow connection) and accessibility (whether or not people can interact with it at all) with this particular markup and styling.

### CODE REVIEW

**Comment by rentry** [comment]
If you still want to merge this PR, I'll need to pull out the dependency updates (which broke Netlify in another PR, but are necessary to run the codebase locally).

**Comment by shannonmcharg** [comment]
@inomyabcs What do you think about simplifying this page so it doesn’t need custom code?

**Comment by inomyabcs** [comment]
Sure. I appreciate the look. I can definitely take away the animations and work to improve the performance.

**Comment by rentry** [comment]
@inomyabcs If you want, you can follow the structure in this pull request for how the break up the files to integrate it into the theme. It's not quite perfect; for example, the vertical lines don't "touch" the subsequent boxes because of global margin themes, but I think it's pretty close to what you had in mind (hopefully).

I'm going to close this pull request, because it includes dependency updates that I needed to get the site working, but that (when pushed independently) broke the Netlify build for some reason. That might be something we need to figure out down the road! But the closed pull request will be here for reference.

Good luck! It really is a cool chart!

**Pull request closed without merging**
